const R=window.RECIPES;
const Q=[
 {k:"mood",e:"START WITH A VIBE",t:"What's calling your name?",s:"Pick what sounds good.",c:[["🍔","Indulgent","I want the good stuff","indulgent"],["🌶️","Bold & spicy","Bring the flavor","bold"],["🥗","Fresh & light","Clean and bright","fresh"],["🍜","Cozy","Comfort me","cozy"],["🥩","Hearty","I am hungry","hearty"],["⚡","Quick","Feed me fast","quick"]]},
 {k:"cuisine",e:"CHOOSE A DIRECTION",t:"Where are we going?",s:"Pick a cuisine — or keep the world open.",c:[["🇮🇹","Italian","Pasta & more","Italian"],["🇲🇽","Mexican","Tacos & heat","Mexican"],["🇯🇵","Japanese","Umami & precision","Japanese"],["🇰🇷","Korean","Big bold flavor","Korean"],["🇹🇭","Thai","Fragrant & vibrant","Thai"],["🌎","Anything","Surprise me","Anything"]]},
 {k:"flavor",e:"TUNE THE FLAVOR",t:"What flavor sounds best?",s:"Choose the direction your taste buds want.",c:[["🧂","Savory","Deep & satisfying","savory"],["🌶️","Spicy","Turn up the heat","spicy"],["🧈","Creamy","Rich & silky","creamy"],["🍋","Tangy","Bright & punchy","tangy"],["🍯","Sweet & savory","A little balance","sweet"],["🔥","Smoky","Charred & grilled","smoky"]]},
 {k:"protein",e:"PICK YOUR CENTERPIECE",t:"What's on the plate?",s:"Choose a centerpiece, or let us decide.",c:[["🍗","Chicken","Always a good idea","chicken"],["🥩","Beef","Big and hearty","beef"],["🍤","Seafood","Light or luxurious","fish"],["🥚","Eggs","Fast & flexible","egg"],["🌱","Plant-based","Beans & grains","plant"],["🎲","Surprise me","You choose","any"]]},
 {k:"effort",e:"LAST QUESTION",t:"How much work?",s:"How ambitious are we feeling tonight?",c:[["⚡","15 minutes","No time to waste","15"],["🍳","30 minutes","A normal dinner","30"],["👨‍🍳","45+ minutes","Let's actually cook","45"],["🎲","Surprise me","You decide","any"]]}
];
let st={i:0,p:{},results:[]};
let saved=JSON.parse(localStorage.getItem("crave_saved")||"[]");
let taste=JSON.parse(localStorage.getItem("crave_taste")||'{"cooked":0,"saved":0,"flavors":{}}');
const $=x=>document.getElementById(x), hide=x=>$(x).classList.add("hidden"), show=x=>$(x).classList.remove("hidden");
function home(){["quiz","results","recipe","saved","profilePage"].forEach(hide);show("home");scrollTo(0,0)}
function startQuiz(){["home","results","recipe","saved","profilePage"].forEach(hide);show("quiz");st={i:0,p:{},results:[]};renderQ();scrollTo(0,0)}
function renderQ(){let q=Q[st.i];$("progress").textContent=`${st.i+1} / ${Q.length}`;$("bar").style.width=`${(st.i+1)/Q.length*100}%`;$("qe").textContent=q.e;$("qt").textContent=q.t;$("qs").textContent=q.s;$("choices").innerHTML=q.c.map(x=>`<button class="choice" onclick="pick('${q.k}','${x[3]}')"><span>${x[0]}</span><div><strong>${x[1]}</strong><small>${x[2]}</small></div></button>`).join("")}
function pick(k,v){st.p[k]=v;if(k==="flavor"){taste.flavors[v]=(taste.flavors[v]||0)+1;saveTaste()}if(st.i<Q.length-1){st.i++;renderQ()}else results()}
function back(){if(st.i){st.i--;renderQ()}}
function score(r){let s=Math.random();if(st.p.mood&&r.mood===st.p.mood)s+=5;if(st.p.cuisine&&st.p.cuisine!=="Anything"&&r.cuisine===st.p.cuisine)s+=7;if(st.p.flavor&&r.flavors.includes(st.p.flavor))s+=5;if(st.p.protein&&st.p.protein!=="any"&&r.ingredients.some(x=>x.toLowerCase().includes(st.p.protein)))s+=3;if(st.p.effort&&st.p.effort!=="any"){let e=+st.p.effort;if(e===15&&r.time<=20)s+=4;if(e===30&&r.time>=20&&r.time<=35)s+=4;if(e===45&&r.time>=35)s+=4}for(let f in taste.flavors)if(r.flavors.includes(f))s+=Math.min(taste.flavors[f],3);return s}
function results(){hide("quiz");show("results");st.results=[...R].sort((a,b)=>score(b)-score(a));let p=Object.values(st.p).filter(x=>!["Anything","any"].includes(x));$("summary").textContent=`You picked ${p.join(" · ")}. Here are six dishes matched to that craving, with a little help from what you've liked before.`;cards(st.results.slice(0,6),"cards");scrollTo(0,0)}
function shuffle(){st.results=[...R].sort(()=>Math.random()-.5);cards(st.results.slice(0,6),"cards")}
function cards(list,id){$(id).innerHTML=list.map(r=>`<article class="card"><div class="card-img"><img src="${r.img}" alt="${r.title}" loading="lazy"><button class="heart" onclick="save('${r.id}',event)">${saved.includes(r.id)?"♥":"♡"}</button></div><div class="body"><div class="meta">${r.cuisine} · ${r.time} min · ${r.difficulty}</div><h3>${r.title}</h3><p class="desc">${r.desc}</p><div class="tags">${r.flavors.map(f=>`<span class="tag">${f}</span>`).join("")}</div><button class="view" onclick="recipe('${r.id}')">View recipe →</button></div></article>`).join("")}
function recipe(id){let r=R.find(x=>x.id===id);["home","quiz","results","saved","profilePage"].forEach(hide);show("recipe");$("recipe").innerHTML=`<button class="back" onclick="showResults()">← Back to your picks</button><div class="detail"><div class="detail-img"><img src="${r.img}" alt="${r.title}"></div><div><div class="eyebrow">${r.cuisine.toUpperCase()}</div><h2>${r.title}</h2><p class="detail-desc">${r.desc}</p><span class="pill">⏱ ${r.time} min</span><span class="pill">★ ${r.difficulty}</span><span class="pill">🍽 4 servings</span><br><button class="save" onclick="save('${r.id}')">${saved.includes(r.id)?"♥ Saved":"♡ Save recipe"}</button><button class="cook" onclick="cook('${r.id}')">▶ Cook mode</button><h3>Ingredients</h3><ul class="ingredients">${r.ingredients.map(x=>`<li>${x}</li>`).join("")}</ul><h3>Let's cook</h3><ol class="steps">${r.steps.map(x=>`<li>${x}</li>`).join("")}</ol></div></div>`;scrollTo(0,0)}
function save(id,e){if(e)e.stopPropagation();saved.includes(id)?(saved=saved.filter(x=>x!==id),toast("Removed from saved")):(saved.push(id),toast("Saved for later"));localStorage.setItem("crave_saved",JSON.stringify(saved));taste.saved=saved.length;saveTaste();update();if(!$("results").classList.contains("hidden"))cards(st.results.slice(0,6),"cards");if(!$("saved").classList.contains("hidden"))renderSaved()}
function update(){$("savedCount").textContent=saved.length}
function savedPage(){["home","quiz","results","recipe","profilePage"].forEach(hide);show("saved");renderSaved();scrollTo(0,0)}
function renderSaved(){let a=R.filter(x=>saved.includes(x.id));$("savedCards").innerHTML=a.length?cards(a,"savedCards"):`<div style="grid-column:1/-1;text-align:center;padding:60px;color:#79756e">♡<h3>Nothing saved yet.</h3><p>Heart a recipe and it will live here.</p></div>`}
function showResults(){hide("recipe");hide("saved");hide("profilePage");show("results");cards(st.results.slice(0,6),"cards");scrollTo(0,0)}
function profilePage(){["home","quiz","results","recipe","saved"].forEach(hide);show("profilePage");let fav=Object.entries(taste.flavors).sort((a,b)=>b[1]-a[1])[0];$("stats").innerHTML=`<div class="stat"><strong>${taste.cooked}</strong><small>recipes cooked</small></div><div class="stat"><strong>${taste.saved}</strong><small>recipes saved</small></div><div class="stat"><strong>${fav?fav[0]:"—"}</strong><small>favorite flavor</small></div>`;scrollTo(0,0)}
function resetTaste(){taste={cooked:0,saved:saved.length,flavors:{}};saveTaste();profilePage();toast("Taste profile reset")}
function saveTaste(){localStorage.setItem("crave_taste",JSON.stringify(taste))}
function cook(id){let r=R.find(x=>x.id===id),i=0,o=document.createElement("div");o.className="cook-overlay";o.innerHTML=`<div class="cook-inner"><div class="cook-top"><strong>✦ Crave · Cook Mode</strong><button class="close" id="cx">×</button></div><div class="cookbar"><b id="cb"></b></div><div class="eyebrow">${r.title.toUpperCase()}</div><h2 id="ct">Let's cook.</h2><p class="cook-text" id="ctxt">One step at a time. No scrolling.</p><div class="cook-actions"><small id="cn">Step 0 of ${r.steps.length}</small><button class="next" id="nx">Start →</button></div></div>`;document.body.appendChild(o);o.querySelector("#cx").onclick=()=>o.remove();o.querySelector("#nx").onclick=()=>{if(i<r.steps.length){$("ct").textContent=`Step ${i+1}`;$("ctxt").textContent=r.steps[i];i++;$("cb").style.width=i/r.steps.length*100+"%";$("cn").textContent=`Step ${i} of ${r.steps.length}`;$("nx").textContent=i===r.steps.length?"Finish":"Next →"}else{taste.cooked++;saveTaste();o.remove();toast("Dinner complete. Nice work.")}}}
function toast(m){let t=$("toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
update();